### ISSUE TITLE
API Version

### ISSUE THREAD

**Issue by Momonche** [RelumCommunity/InfiniteAnvil#1]
**Describe the bug**
Add the API Version in plugin.yml to prevent a legacy data load on startup

**Expected behavior**
No legacy data load

**Server (please complete the following information):**
git-Paper-378 (MC: 1.15.2)

**Comment by RelumCommunity** [comment]
Ok, i need to sorry cause i missed out your issue request, tomorrow we will release an update fixing this issue and testing it with 1.20.x too.
We are back since the beginning of october after a big 3/4 years stop

**Comment by RelumCommunity** [comment]
fixed
